#!/bin/bash
# ───────────────────────────────────────────────────────────────
# A.L.E.C. — Full Local Setup (first-time)
# Sets up Node.js deps, Python venv, model download, and .env.
# ───────────────────────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo "🚀 A.L.E.C. — Full Local Setup"
echo "   Project: $PROJECT_DIR"
echo ""

# ── 1. Check prerequisites ──────────────────────────────────────
echo "── Checking prerequisites ──"

if ! command -v node &> /dev/null; then
    echo "❌ Node.js not found. Install Node.js 18+ from https://nodejs.org/"
    exit 1
fi
echo "✅ Node.js $(node --version)"

if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 not found. Install Python 3.11+ from https://python.org/"
    exit 1
fi
echo "✅ Python $(python3 --version)"

if ! command -v pip3 &> /dev/null && ! command -v pip &> /dev/null; then
    echo "❌ pip not found."
    exit 1
fi

echo ""

# ── 2. Create directory structure ────────────────────────────────
echo "── Creating directories ──"
mkdir -p data/models data/models/lora data/models/checkpoints data/sft data/context
mkdir -p logs chat history skills smarthome tokens

touch data/models/.gitkeep logs/.gitkeep

echo "✅ Directory structure ready"
echo ""

# ── 3. Install Node.js dependencies ─────────────────────────────
echo "── Installing Node.js dependencies ──"
npm install
echo "✅ Node.js deps installed"
echo ""

# ── 4. Python virtual environment ───────────────────────────────
echo "── Setting up Python venv ──"
VENV_DIR="$PROJECT_DIR/services/neural/.venv"

if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    echo "✅ Created venv at $VENV_DIR"
else
    echo "ℹ️  venv already exists"
fi

source "$VENV_DIR/bin/activate"

# Upgrade pip
pip install --upgrade pip

# Detect Apple Silicon for Metal support
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
    echo "🍎 Apple Silicon detected — installing llama-cpp-python with Metal"
    CMAKE_ARGS="-DLLAMA_METAL=on" pip install llama-cpp-python
else
    echo "Installing llama-cpp-python (CPU)"
    pip install llama-cpp-python
fi

# Install remaining Python deps
pip install -r services/neural/requirements.txt

echo "✅ Python dependencies installed"
echo ""

# ── 5. Download model ────────────────────────────────────────────
echo "── Downloading model ──"
bash scripts/download-model.sh
echo ""

# ── 6. Create .env file ─────────────────────────────────────────
echo "── Environment configuration ──"
if [ ! -f .env ]; then
    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")

    cat > .env << EOF
# A.L.E.C. Configuration — generated by setup-local.sh
NODE_ENV=development

# Server ports
PORT=3001
NEURAL_PORT=8000
HOST=0.0.0.0

# JWT (auto-generated — keep secret)
JWT_SECRET=$JWT_SECRET

# Model configuration
MODEL_PATH=data/models/qwen2.5-coder-7b-instruct-q4_k_m.gguf
MODEL_CONTEXT_LENGTH=4096
N_GPU_LAYERS=-1
NEURAL_BACKEND=llama-cpp

# Azure SQL (optional — SQLite fallback is automatic)
# AZURE_SQL_CONNECTION_STRING=Server=tcp:stoagroupdb.database.windows.net,1433;...

# Voice
VOICE_INTERFACE_ENABLED=true
EOF
    echo "✅ Created .env (JWT secret auto-generated)"
else
    echo "ℹ️  .env already exists (skipping)"
fi

echo ""
echo "═══════════════════════════════════════════════════════"
echo " ✅ A.L.E.C. setup complete!"
echo ""
echo " Start everything:  bash scripts/start-alec.sh"
echo ""
echo " Or start manually:"
echo "   Terminal 1: cd services/neural && source .venv/bin/activate && python server.py"
echo "   Terminal 2: node backend/server.js"
echo ""
echo " Frontend:  http://localhost:3001"
echo " API:       http://localhost:3001/api/chat"
echo " Neural:    http://localhost:8000/health"
echo "═══════════════════════════════════════════════════════"
